name: limesdr-urh
version: 1.6.2.2
summary: LimeSuite + Universal Radio Hacker
description: LimeSuite driver, SoapySDR, URH
confinement: strict
grade: stable

environment:
    LIME_SUITE_ROOT: $SNAP
    SOAPY_SDR_ROOT: $SNAP
    APPDATA: $SNAP_USER_COMMON
    VOLK_CONFIGPATH: $SNAP_USER_COMMON
    VOLK_PREFIX: $SNAP
    GR_PREFIX: $SNAP

apps:

    SoapySDRUtil:
        command: SoapySDRUtil
        plugs: [network]

    urh:
        command: desktop-launch urh
        plugs: [network, x11, pulseaudio, opengl, home, unity7]

    gnuradio-config-info:
        command: gnuradio-config-info

    volk-config-info:
        command: volk-config-info

    volk-profile:
        command: volk_profile

parts:
    soapysdr:
        plugin: cmake
        source: https://github.com/pothosware/SoapySDR.git
        source-branch: maint
        configflags:
            - -DENABLE_PYTHON3=OFF
            - -DENABLE_PYTHON=OFF

    soapyremote:
        plugin: cmake
        source: https://github.com/pothosware/SoapyRemote.git
        source-branch: maint
        after: [soapysdr]

    limesuite:
        plugin: cmake
        source: https://github.com/myriadrf/LimeSuite.git
        source-branch: stable
        configflags:
            - -DENABLE_GUI=OFF
            - -DDOWNLOAD_IMAGES=TRUE
        after: [soapysdr]
        build-packages:
            - libsqlite3-dev
            - libi2c-dev
            - libusb-1.0-0-dev

    volk:
        plugin: cmake
        source: https://github.com/gnuradio/volk.git
        source-branch: master #must be master for now for VOLK_PREFIX
        build-packages: [libboost-all-dev, liborc-0.4-dev]
        after: [pythonmodules]

    gnuradio:
        plugin: cmake
        source: https://github.com/gnuradio/gnuradio.git
        source-branch: maint
        build-packages:
            - libasound2-dev
            - libboost-all-dev
            - libcodec2-dev
            - libcomedi-dev
            - libfftw3-dev
            - libfontconfig1-dev
            - libgsl-dev
            - libgsm1-dev
            - libjack-jackd2-dev
            - liblog4cpp5-dev
            - libpulse-dev
            - libqt4-dev
            - libqwt5-qt4-dev
            - libsdl1.2-dev
            - libsndfile1-dev
            - libxi-dev
            - libxrender-dev
            - libzmq3-dev
            - portaudio19-dev
        configflags:
            - -DENABLE_PYTHON=OFF
            - -DENABLE_TESTING=OFF
            - -DENABLE_INTERNAL_VOLK=OFF
            - -DENABLE_DOXYGEN=OFF
            - -DENABLE_SPHINX=OFF
            - -DENABLE_GR_QTGUI=OFF
            - -DENABLE_GR_WXGUI=OFF
        after: [volk]

    grosmosdr:
        plugin: cmake
        source: git://git.osmocom.org/gr-osmosdr
        build-packages: [libboost-all-dev]
        configflags:
            - -DENABLE_PYTHON=OFF
        after: [soapysdr, gnuradio]

    urh:
        plugin: python
        source: https://github.com/jopohl/urh.git
        build-packages: [libhackrf-dev]
        stage-packages:
          - python3-numpy
          - python3-psutil
          - python3-zmq
          - python3-pyqt5
        after: [limesuite, soapysdr, gnuradio, desktop-qt5]


    pythonmodules:
        plugin: nil
        stage-packages:
            - python
            - python-six
            - python-cheetah
            - python-mako
